slack_token: "your-slack-bot-token"
openai_api_key: "your-openai-api-key"
model_name: "gpt-3.5-turbo"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
faiss_index_path: "data/index.faiss"
docstore_path: "data/docstore.pkl"
kb_articles_path: "data/kb_articles.json"
feedback_threshold: 0.7